### ISSUE TITLE
Create all epub 

### ISSUE THREAD

**Issue by cittadhammo** [buddhiko1/pali-epub#3]
Hi, 

Thank you for your app, it works great !

I was wondering if there is a simple way to create all the epub at once for all the collections. I had a look at the index.ts and it would simply require to have a loop trough all the collections.forEach(d=> ...)

could you help me with that ?

Thanks !
This would be very helpful as I could have all of them on my eReader for study.

**Comment by Nirodhiko** [comment]
@cittadhammo 
ok ~
That's what I plan to do, but i don't have time recently. I'll finish it in two weeks.
If you don't like the font color, you can modify the base.css file and then regenerate it.

**Comment by cittadhammo** [comment]
That is great. I'm not in a hurry. If a good complete output is made, you could ask to add it to https://readingfaithfully.org/

**Comment by Nirodhiko** [comment]
@cittadhammo 
hello ~
I have added the feature and updated the readme.md .
You can create all the epub at once with `ts-node ./index -a`  after run `git pull` and `pnpm install` .

**Comment by Nirodhiko** [comment]
@cittadhammo 
My english is very poor. 
If anyone needs it, you can help add it.

**Comment by cittadhammo** [comment]
> @cittadhammo My english is very poor. If anyone needs it, you can help add it.

Good thank you so much !
